"""Evaluación del modelo (#31). Especificación: `docs/arquitectura/04-evaluar-niveles-0-1.md`."""

from gepp_vision.evaluacion.acuerdo import (
    KAPPA_MINIMO,
    SIN_CAJA,
    Acuerdo,
    acuerdo,
    bajo_el_minimo,
    imagenes_de_la_segunda,
    kappa_cohen,
)
from gepp_vision.evaluacion.coco import (
    CLASES,
    ArchivoCoco,
    CajaPx,
    EntradaInvalida,
    Recorte,
    en_region,
    imagenes_comunes,
    leer_coco,
)
from gepp_vision.evaluacion.deteccion import (
    MAX_DETS,
    TAMANOS,
    UMBRAL_IOU,
    UMBRAL_REGLA,
    MetricasClase,
    MetricasRegion,
    evaluar,
    evaluar_regiones,
)
from gepp_vision.evaluacion.reporte import (
    LIMITACIONES_ACUERDO,
    ORIGENES,
    estado_git,
    reporte,
    reporte_acuerdo,
    sha256,
    tabla_acuerdo,
    tabla_markdown,
)

__all__ = [
    "CLASES",
    "KAPPA_MINIMO",
    "LIMITACIONES_ACUERDO",
    "MAX_DETS",
    "ORIGENES",
    "SIN_CAJA",
    "TAMANOS",
    "UMBRAL_IOU",
    "UMBRAL_REGLA",
    "Acuerdo",
    "ArchivoCoco",
    "CajaPx",
    "EntradaInvalida",
    "MetricasClase",
    "MetricasRegion",
    "Recorte",
    "acuerdo",
    "bajo_el_minimo",
    "en_region",
    "estado_git",
    "evaluar",
    "evaluar_regiones",
    "imagenes_comunes",
    "imagenes_de_la_segunda",
    "kappa_cohen",
    "leer_coco",
    "reporte",
    "reporte_acuerdo",
    "sha256",
    "tabla_acuerdo",
    "tabla_markdown",
]
