/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hallazgos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista de hallazgos para la bandeja de triage
         * @description Devuelve la página de hallazgos y, en `contadores`, el total de cada pestaña **con los
         *     mismos filtros aplicados salvo `estado`** — así las pestañas no mienten al filtrar.
         */
        get: operations["listarHallazgos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hallazgos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un hallazgo, para el visor de evidencia */
        get: operations["obtenerHallazgo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hallazgos/{id}/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolver un hallazgo
         * @description Registra la decisión humana. Queda en `auditoria`, que es append-only: es lo que permite
         *     acreditar quién validó qué y cuándo.
         */
        post: operations["triarHallazgo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hallazgos/triage-lote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolver varios hallazgos a la vez
         * @description Sostiene la barra flotante de acciones en lote de la bandeja.
         */
        post: operations["triarLote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hallazgos/{id}/acciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asignar una acción correctiva
         * @description Cierra el ciclo. Sin esto el sistema produce ruido, no seguridad.
         */
        post: operations["crearAccionCorrectiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cola de ingesta */
        get: operations["listarVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/reprocesar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocesar un video
         * @description Idempotente por `hash_sha256`: reprocesar no duplica hallazgos, los reemplaza. Es lo que
         *     permite recalcular reglas sin volver a tocar la GPU.
         */
        post: operations["reprocesarVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las tres bandas de la portada, en una sola llamada
         * @description Una llamada y no cinco, porque la portada se pinta de una vez o parpadea.
         */
        get: operations["obtenerPanel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reglas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de reglas */
        get: operations["listarReglas"];
        put?: never;
        /** Crear una regla */
        post: operations["crearRegla"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reglas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una regla */
        get: operations["obtenerRegla"];
        /**
         * Editar una regla — crea una versión nueva
         * @description **No modifica la versión vigente: crea la siguiente y desactiva la anterior.** Sin esto,
         *     en la defensa nadie puede explicar por qué un hallazgo de la S8 se disparó con un umbral
         *     que ya no existe.
         */
        put: operations["actualizarRegla"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reglas/{id}/simular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * "¿Y si...?" — simular la regla sobre el histórico
         * @description Recalcula la regla sobre las **detecciones ya persistidas**, sin GPU y sin volver a leer
         *     video. Es el botón "Simular sobre los últimos 30 días" del editor.
         */
        post: operations["simularRegla"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/{tipo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reporte agregado
         * @description Las celdas cuya población es menor que 5 se devuelven con `datos_insuficientes: true` y
         *     **sin valor**. La supresión ocurre en el servidor: el frontend no puede saltársela.
         */
        get: operations["obtenerReporte"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obras, áreas, zonas, fuentes y turnos, de una vez
         * @description Alimenta todos los selectores de la aplicación. Se pide una vez al arrancar.
         */
        get: operations["obtenerCatalogos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de ingesta y cobertura, para la cabecera global
         * @description Llamada barata y frecuente: la cabecera vive en todas las pantallas, así que no puede
         *     depender de `/panel`. Pensada para consultarse cada pocos segundos.
         */
        get: operations["obtenerEstado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario de la sesión y sus permisos
         * @description El frontend pinta según `permisos`, no según el rol. El administrador **no** ve evidencia:
         *     es lo que separa a quien configura de quien observa.
         */
        get: operations["obtenerSesion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 1 baja · 2 media · 3 alta · 4 crítica. **Independiente de la confianza.**
         * @example 4
         * @enum {integer}
         */
        Severidad: 1 | 2 | 3 | 4;
        /**
         * @example casco
         * @enum {string}
         */
        TipoEpp: "casco" | "chaleco" | "lentes" | "guantes" | "arnes" | "calzado";
        /**
         * @example por_revisar
         * @enum {string}
         */
        EstadoHallazgo: "por_revisar" | "confirmado" | "falso_positivo" | "duplicado" | "pospuesto";
        /**
         * @description La unidad del sistema. **No es un cuadro con una caja**: es un track, en una zona, durante
         *     un intervalo, que incumplió una regla.
         */
        Hallazgo: {
            /**
             * Format: int64
             * @example 4821
             */
            id: number;
            /**
             * @example {
             *       "id": 3,
             *       "nombre": "Excavación y Fundaciones"
             *     }
             */
            area: components["schemas"]["Referencia"];
            /**
             * @example {
             *       "id": 11,
             *       "nombre": "Borde de excavación"
             *     }
             */
            zona: components["schemas"]["Referencia"];
            /**
             * @example {
             *       "id": 1,
             *       "nombre": "CAM-01 Acceso Obra"
             *     }
             */
            fuente: components["schemas"]["Referencia"];
            /**
             * @example [
             *       "casco",
             *       "chaleco"
             *     ]
             */
            epp_faltante: components["schemas"]["TipoEpp"][];
            /** @example 4 */
            severidad: components["schemas"]["Severidad"];
            /**
             * Format: date-time
             * @description Hora de **captura**.
             * @example 2026-09-03T10:14:07-03:00
             */
            ts_inicio: string;
            /**
             * Format: date-time
             * @description Nulo mientras el evento sigue vivo (solo v2, en vivo).
             * @example 2026-09-03T10:17:19-03:00
             */
            ts_fin?: string | null;
            /**
             * Format: float
             * @example 192
             */
            duracion_s: number;
            /**
             * @description Total de cuadros en que se confirmó el incumplimiento. **Es un entero, no una razón:**
             *     la razón del umbral ("4 de 5 en 2,0 s") pertenece al visor, en `por_que_se_disparo`.
             *     Mostrarla en la bandeja reintroduce el pensamiento en cuadros que el ADR-005 prohíbe.
             *
             *     **Coherencia obligatoria con `duracion_s`:** el sistema muestrea a 5 fps, así que este
             *     valor ronda `duracion_s × 5`. Un hallazgo de 192 s tiene del orden de 900 cuadros
             *     confirmados, no 47. Si la razón entre ambos no da ~5, uno de los dos está mal.
             * @example 912
             */
            cuadros_confirmados: number;
            /**
             * Format: float
             * @description Eje **separado** de la severidad. Nunca se combinan.
             * @example 0.91
             */
            confianza_media: number;
            estado: components["schemas"]["EstadoHallazgo"];
            /**
             * Format: uri-reference
             * @description Recorte 64×36 **ya anonimizado**.
             * @example /api/v1/evidencias/9912/miniatura
             */
            miniatura_url?: string | null;
            /** @example null */
            asignado_a?: components["schemas"]["Referencia"];
            /**
             * @description La zona acumula más de un hallazgo en la ventana consultada.
             * @example true
             */
            reincidente?: boolean;
            /**
             * @description Se muestra en cada hallazgo, sin excepción.
             * @default Indicio automatizado. Requiere validación humana.
             * @example Indicio automatizado. Requiere validación humana.
             */
            aviso_legal: string;
        };
        HallazgoDetalle: components["schemas"]["Hallazgo"] & {
            /**
             * Format: uri-reference
             * @description Clip de ~8 s en bucle, con el rostro ya difuminado en el archivo.
             * @example /api/v1/evidencias/9912/clip
             */
            recorte_video_url?: string | null;
            evidencias: components["schemas"]["Evidencia"][];
            /** @description Las tres marcas del visor. */
            linea_tiempo?: {
                /** Format: date-time */
                primera_deteccion?: string;
                /** Format: date-time */
                umbral_alcanzado?: string;
                /** Format: date-time */
                fin?: string | null;
            };
            /**
             * @description Etapa 2. **El modelo de lenguaje visual describe; no decide.** Nunca crea, suprime
             *     ni cambia la severidad de un hallazgo (ADR-001).
             */
            descripcion_automatica?: {
                /** @example Trabajador sin casco junto a excavación */
                titulo?: string;
                /** @example Una persona permanece en el borde de la excavación sin casco durante poco más de tres minutos, mientras dos compañeros trabajan con equipo de protección completo. */
                descripcion?: string;
                /**
                 * Format: float
                 * @example 0.72
                 */
                confianza?: number;
                /** @example qwen3-vl-4b-q4 */
                modelo?: string;
            } | null;
            /**
             * @description El bloque que hace auditable el sistema. Sin esto no se puede explicar una alerta,
             *     y una alerta que no se explica no se defiende.
             */
            por_que_se_disparo: {
                /**
                 * Format: int64
                 * @example 12
                 */
                regla_id?: number;
                /** @example Casco obligatorio — Excavación */
                regla_nombre: string;
                /** @example 3 */
                regla_version: number;
                /** @example Excavación y Fundaciones */
                zona?: string;
                epp_exigido?: components["schemas"]["TipoEpp"][];
                /**
                 * @description En segundos, en lenguaje natural. **Nunca en cuadros.**
                 * @example 4 de 5 cuadros en 2,0 s
                 */
                umbral_configurado: string;
                /** @example 912 de 960 cuadros en 192,0 s */
                valores_observados: string;
                /**
                 * Format: float
                 * @example 0.45
                 */
                confianza_minima?: number;
                /** @enum {string} */
                base_licitud?: "obligacion_legal" | "interes_legitimo" | "contrato";
                /** @example DS 594 art. 53 */
                norma_fundante?: string;
            };
            /** @description Metadatos plegados del visor. */
            tecnicos: {
                /** @example CAM-01_2026-09-03_08-00.mp4 */
                video_archivo?: string;
                /** @example 9f2c1a7e…b304 */
                video_hash?: string;
                /**
                 * Format: float
                 * @example 854.4
                 */
                segundo_en_video?: number;
                /**
                 * Format: float
                 * @description Cadencia real de análisis. Las reglas son invariantes a este valor.
                 * @example 5
                 */
                fps_muestreo?: number;
                /** @example rfdetr-b-epp-v3 */
                modelo_version?: string;
                /**
                 * @description **Efímero.** Único dentro de este video y sin significado fuera de él. No se
                 *     cruza entre videos, cámaras ni días.
                 * @example 17
                 */
                track_id?: number;
            };
            acciones?: components["schemas"]["AccionCorrectiva"][];
        };
        PaginaHallazgos: {
            items: components["schemas"]["Hallazgo"][];
            /** @description Totales de cada pestaña, con los mismos filtros salvo `estado`. */
            contadores: {
                /** @example 34 */
                por_revisar?: number;
                /** @example 128 */
                confirmado?: number;
                /** @example 41 */
                descartado?: number;
                /** @example 9 */
                reincidente?: number;
                /** @example 203 */
                todos?: number;
            };
            /** @example null */
            siguiente_cursor?: string | null;
        };
        DecisionTriage: {
            /** @enum {string} */
            estado: "confirmado" | "falso_positivo" | "duplicado" | "pospuesto";
            /**
             * @description Obligatorio para `falso_positivo` — alimenta el análisis de error.
             * @example La persona lleva casco, tapado por el andamio
             */
            motivo?: string;
            /** Format: int64 */
            duplicado_de?: number | null;
            /** Format: date-time */
            posponer_hasta?: string | null;
        };
        Evidencia: {
            /**
             * Format: int64
             * @example 9912
             */
            id: number;
            /** @example 4272 */
            cuadro_idx: number;
            /** Format: date-time */
            capture_ts: string;
            /**
             * @description Siempre `true`. El recorte se escribe ya difuminado; no hay otra versión.
             * @constant
             */
            anonimizado: true;
            /**
             * Format: uri-reference
             * @example /api/v1/evidencias/9912
             */
            url: string;
            /**
             * Format: date
             * @description Calculada desde `regla.retencion_dias`.
             * @example 2026-10-03
             */
            purgar_el?: string;
        };
        AccionCorrectivaNueva: {
            /**
             * Format: int64
             * @example 7
             */
            responsable_id: number;
            /** @example Reponer casco y reinstruir al frente de trabajo */
            descripcion: string;
            /**
             * Format: date
             * @example 2026-09-08
             */
            plazo: string;
        };
        AccionCorrectiva: components["schemas"]["AccionCorrectivaNueva"] & {
            /**
             * Format: int64
             * @example 301
             */
            id?: number;
            /** @enum {string} */
            estado?: "abierta" | "en_curso" | "cerrada" | "vencida";
            /** Format: date-time */
            cerrada_en?: string | null;
            comentario_cierre?: string | null;
        };
        Video: {
            /**
             * Format: int64
             * @example 88
             */
            id: number;
            /** @example CAM-01_2026-09-03_08-00.mp4 */
            archivo: string;
            /** @example 9f2c1a7e */
            hash_abreviado?: string;
            fuente?: components["schemas"]["Referencia"];
            /**
             * Format: float
             * @example 3600
             */
            duracion_s?: number;
            /**
             * Format: int64
             * @example 734003200
             */
            bytes?: number;
            /** @example 1280 */
            ancho?: number;
            /** @example 720 */
            alto?: number;
            /**
             * Format: date-time
             * @description De los metadatos del contenedor o de `mtime - duración`. **Nunca `now()`.**
             */
            capture_ts_inicio: string;
            /**
             * @description Se muestra en la interfaz — un reloj de origen dudoso debe verse.
             * @enum {string}
             */
            origen_capture_ts?: "metadatos" | "mtime" | "manual" | "ocr";
            /** @enum {string} */
            estado: "en_cola" | "procesando" | "listo" | "error";
            /**
             * Format: float
             * @example 0.42
             */
            progreso?: number | null;
            error_motivo?: string | null;
            /**
             * Format: float
             * @example 5
             */
            fps_efectivo?: number | null;
            /** @example 18000 */
            cuadros_analizados?: number | null;
            /**
             * Format: int64
             * @example 412000
             */
            proceso_ms?: number | null;
            /** @example 6 */
            hallazgos_generados?: number;
        };
        Panel: {
            /** @description Las cinco tarjetas, en orden de presentación. */
            indicadores: {
                /** @enum {string} */
                clave: "hallazgos_abiertos" | "criticos_sin_revisar" | "cumplimiento_epp" | "zona_mas_incumplimientos" | "videos_procesados_hoy";
                /** @example Hallazgos abiertos */
                etiqueta: string;
                /** @example 34 */
                valor: number | string;
                /** @example % */
                unidad?: string | null;
                /**
                 * Format: float
                 * @description Contra el período anterior. La interfaz muestra flecha **y** signo.
                 * @example -0.12
                 */
                variacion?: number | null;
                /**
                 * @description Minigráfico de 60×20.
                 * @example [
                 *       12,
                 *       15,
                 *       9,
                 *       18,
                 *       22,
                 *       17,
                 *       14
                 *     ]
                 */
                serie?: number[];
            }[];
            /** @description Máximo cuatro series, una por severidad. */
            tendencia: {
                /**
                 * @example [
                 *       "L",
                 *       "M",
                 *       "M",
                 *       "J",
                 *       "V",
                 *       "S",
                 *       "D"
                 *     ]
                 */
                etiquetas?: string[];
                series?: {
                    severidad?: components["schemas"]["Severidad"];
                    valores?: number[];
                }[];
            };
            /** @description Top 5 más "Otros". */
            ranking_epp: {
                /** @example casco */
                epp?: string;
                /** @example 61 */
                total?: number;
            }[];
            criticos_recientes: components["schemas"]["Hallazgo"][];
            cobertura: components["schemas"]["Cobertura"];
        };
        /**
         * @description **El hueco tiene que verse.** Si el sistema no está mirando una zona, el prevencionista
         *     debe saberlo: es la mitigación del riesgo de falso negativo con complacencia.
         */
        Cobertura: {
            /** @example 3 */
            fuentes_activas?: number;
            /** @example 4 */
            fuentes_totales?: number;
            sin_cobertura?: {
                fuente?: components["schemas"]["Referencia"];
                /** @enum {string} */
                motivo?: "sin_ingesta" | "requiere_recalibracion" | "error" | "regla_degradada";
                /** Format: date-time */
                desde?: string;
            }[];
        };
        ReglaEntrada: {
            /** @example Casco obligatorio — Excavación */
            nombre: string;
            /**
             * Format: int64
             * @example 3
             */
            area_id: number;
            zona_ids?: number[];
            /**
             * @example [
             *       "casco"
             *     ]
             */
            epp_exigido: components["schemas"]["TipoEpp"][];
            /**
             * Format: float
             * @description **Segundos, nunca cuadros.** Los cuadros se derivan en ejecución: así la misma regla
             *     significa lo mismo a 2, 5, 10 o 15 fps.
             * @example 2
             */
            confirmacion_segundos: number;
            /**
             * Format: float
             * @default 3
             */
            cierre_segundos: number;
            /**
             * Format: float
             * @default 0.45
             */
            confianza_minima: number;
            severidad: components["schemas"]["Severidad"];
            /** @example A */
            turno?: string | null;
            /** @example 08:00 */
            hora_desde?: string | null;
            /** @example 17:30 */
            hora_hasta?: string | null;
            /** @default true */
            activa: boolean;
            /**
             * @default obligacion_legal
             * @enum {string}
             */
            base_licitud: "obligacion_legal" | "interes_legitimo" | "contrato";
            /** @example DS 594 art. 53 */
            norma_fundante?: string;
            /** @example Prevención de lesiones por caída de objetos */
            finalidad_declarada: string;
            /** @default 30 */
            retencion_dias: number;
            destinatarios?: number[];
            /**
             * @description Sostiene el presupuesto de ≤6 avisos por turno de 12 h (ADR-008).
             * @example 900
             */
            espera_entre_alertas_s?: number;
        };
        Regla: components["schemas"]["ReglaEntrada"] & {
            /**
             * Format: int64
             * @example 12
             */
            id: number;
            /** @example 3 */
            version: number;
            /** @example 47 */
            hallazgos_30d?: number;
            /**
             * @description Falso cuando la cámara no resuelve el EPP exigido en esa zona (tabla
             *     `zona × EPP × evaluable`, V2). **El motor nunca exige lo que la cámara no ve.**
             * @example true
             */
            evaluable?: boolean;
            /** Format: date-time */
            creada_en?: string;
        };
        ResultadoSimulacion: {
            /** @example 47 */
            hallazgos_estimados: number;
            contra_version_vigente?: {
                /** @example 61 */
                actuales?: number;
                /** @example -14 */
                variacion?: number;
            };
            /**
             * @example {
             *       "2": 22,
             *       "3": 19,
             *       "4": 6
             *     }
             */
            por_severidad?: {
                [key: string]: number;
            };
            ejemplos?: components["schemas"]["Evidencia"][];
            /**
             * Format: float
             * @description Contra el presupuesto de ≤6 por turno de 12 h.
             * @example 4.2
             */
            alertas_por_turno_estimadas?: number;
        };
        Reporte: {
            /** @example ranking-epp */
            tipo: string;
            /** @example zona */
            segmentacion?: string | null;
            filas: {
                /** @example Andamio Fachada Norte */
                etiqueta: string;
                /** @example 23 */
                valor?: number | null;
                /**
                 * @description Población de la celda.
                 * @example 18
                 */
                n?: number | null;
                /**
                 * @description `true` cuando n < 5. En ese caso `valor` viene nulo y la interfaz muestra
                 *     "datos insuficientes". La supresión es del servidor.
                 * @default false
                 */
                datos_insuficientes: boolean;
                /** @description Minigráfico de 8 semanas, en el ranking por zona. */
                serie?: number[];
            }[];
        };
        Catalogos: {
            obras?: components["schemas"]["Referencia"][];
            areas?: components["schemas"]["Referencia"][];
            zonas?: components["schemas"]["Referencia"][];
            fuentes?: components["schemas"]["Referencia"][];
            turnos?: {
                /** @example A */
                codigo?: string;
                /** @example Turno A (08:00-17:30) */
                etiqueta?: string;
            }[];
            epp?: components["schemas"]["TipoEpp"][];
        };
        Sesion: {
            /**
             * Format: int64
             * @example 7
             */
            id: number;
            /** @example Edgar Tolentino */
            nombre: string;
            /**
             * @example prevencionista
             * @enum {string}
             */
            rol: "administrador" | "prevencionista" | "supervisor" | "auditor";
            /**
             * Format: int64
             * @description El supervisor solo ve su área.
             */
            area_id?: number | null;
            /**
             * @description El frontend se pinta contra esta lista, no contra el rol. `ver_evidencia` no lo tiene
             *     el administrador: quien configura no observa.
             *     No existe ningún permiso de descarga masiva de recortes.
             * @example [
             *       "ver_hallazgos",
             *       "triar_hallazgos",
             *       "ver_evidencia",
             *       "ver_reportes",
             *       "asignar_acciones"
             *     ]
             */
            permisos: ("ver_hallazgos" | "triar_hallazgos" | "ver_evidencia" | "editar_reglas" | "ver_reportes" | "ver_auditoria" | "asignar_acciones")[];
        };
        /** @description Identificador y nombre para pintar. Nunca datos de una persona trabajadora. */
        Referencia: {
            /**
             * Format: int64
             * @example 3
             */
            id?: number;
            /** @example Excavación y Fundaciones */
            nombre?: string;
        } | null;
        Error: {
            /** @example hallazgo_ya_resuelto */
            codigo: string;
            /** @example Otro usuario resolvió este hallazgo hace 2 minutos */
            mensaje: string;
            detalle?: Record<string, never> | null;
        };
    };
    responses: {
        /** @description Petición rechazada */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Falta o caducó la sesión */
        NoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El rol no alcanza. El administrador no accede a evidencia. */
        SinPermiso: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No existe */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        HallazgoId: number;
        ReglaId: number;
        Estado: components["schemas"]["EstadoHallazgo"];
        /** @description 4 crítica · 3 alta · 2 media · 1 baja */
        Severidad: components["schemas"]["Severidad"][];
        AreaId: number;
        ZonaId: number;
        FuenteId: number;
        ObraId: number;
        /** @description Filtra por EPP faltante. */
        Epp: components["schemas"]["TipoEpp"][];
        /** @description Hora de **captura**, no de procesamiento. */
        Desde: string;
        Hasta: string;
        Turno: string;
        Limite: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarHallazgos: {
        parameters: {
            query?: {
                estado?: components["parameters"]["Estado"];
                /** @description 4 crítica · 3 alta · 2 media · 1 baja */
                severidad?: components["parameters"]["Severidad"];
                area_id?: components["parameters"]["AreaId"];
                zona_id?: components["parameters"]["ZonaId"];
                fuente_id?: components["parameters"]["FuenteId"];
                /** @description Filtra por EPP faltante. */
                epp?: components["parameters"]["Epp"];
                /** @description Hora de **captura**, no de procesamiento. */
                desde?: components["parameters"]["Desde"];
                hasta?: components["parameters"]["Hasta"];
                turno?: components["parameters"]["Turno"];
                /** @description Solo hallazgos en zonas con más de un hallazgo en la ventana consultada. */
                reincidente?: boolean;
                orden?: "ts_inicio_desc" | "ts_inicio_asc" | "severidad_desc" | "duracion_desc" | "confianza_desc";
                limite?: components["parameters"]["Limite"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de hallazgos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 4821,
                     *           "area": {
                     *             "id": 5,
                     *             "nombre": "Andamio Fachada Norte"
                     *           },
                     *           "zona": {
                     *             "id": 14,
                     *             "nombre": "Plataforma nivel 4"
                     *           },
                     *           "fuente": {
                     *             "id": 4,
                     *             "nombre": "CAM-04 Fachada Norte"
                     *           },
                     *           "epp_faltante": [
                     *             "arnes"
                     *           ],
                     *           "severidad": 4,
                     *           "ts_inicio": "2026-09-03T10:14:07-03:00",
                     *           "ts_fin": "2026-09-03T10:17:19-03:00",
                     *           "duracion_s": 192,
                     *           "cuadros_confirmados": 912,
                     *           "confianza_media": 0.91,
                     *           "estado": "por_revisar",
                     *           "miniatura_url": "/api/v1/evidencias/9912/miniatura",
                     *           "asignado_a": null,
                     *           "reincidente": true,
                     *           "aviso_legal": "Indicio automatizado. Requiere validación humana."
                     *         },
                     *         {
                     *           "id": 4820,
                     *           "area": {
                     *             "id": 3,
                     *             "nombre": "Excavación y Fundaciones"
                     *           },
                     *           "zona": {
                     *             "id": 11,
                     *             "nombre": "Borde de excavación"
                     *           },
                     *           "fuente": {
                     *             "id": 1,
                     *             "nombre": "CAM-01 Acceso Obra"
                     *           },
                     *           "epp_faltante": [
                     *             "casco"
                     *           ],
                     *           "severidad": 4,
                     *           "ts_inicio": "2026-09-03T08:22:40-03:00",
                     *           "ts_fin": "2026-09-03T08:24:27-03:00",
                     *           "duracion_s": 107,
                     *           "cuadros_confirmados": 508,
                     *           "confianza_media": 0.88,
                     *           "estado": "por_revisar",
                     *           "miniatura_url": "/api/v1/evidencias/9908/miniatura",
                     *           "asignado_a": null,
                     *           "reincidente": false,
                     *           "aviso_legal": "Indicio automatizado. Requiere validación humana."
                     *         },
                     *         {
                     *           "id": 4817,
                     *           "area": {
                     *             "id": 7,
                     *             "nombre": "Patio de Maniobras"
                     *           },
                     *           "zona": {
                     *             "id": 21,
                     *             "nombre": "Zona de descarga"
                     *           },
                     *           "fuente": {
                     *             "id": 9,
                     *             "nombre": "CAM-09 Patio"
                     *           },
                     *           "epp_faltante": [
                     *             "chaleco"
                     *           ],
                     *           "severidad": 3,
                     *           "ts_inicio": "2026-09-03T07:41:55-03:00",
                     *           "ts_fin": "2026-09-03T07:42:43-03:00",
                     *           "duracion_s": 48,
                     *           "cuadros_confirmados": 228,
                     *           "confianza_media": 0.76,
                     *           "estado": "por_revisar",
                     *           "miniatura_url": "/api/v1/evidencias/9901/miniatura",
                     *           "asignado_a": null,
                     *           "reincidente": false,
                     *           "aviso_legal": "Indicio automatizado. Requiere validación humana."
                     *         },
                     *         {
                     *           "id": 4802,
                     *           "area": {
                     *             "id": 6,
                     *             "nombre": "Losa Nivel 3"
                     *           },
                     *           "zona": {
                     *             "id": 18,
                     *             "nombre": "Frente de hormigonado"
                     *           },
                     *           "fuente": {
                     *             "id": 7,
                     *             "nombre": "CAM-07 Losa N3"
                     *           },
                     *           "epp_faltante": [
                     *             "casco",
                     *             "chaleco"
                     *           ],
                     *           "severidad": 3,
                     *           "ts_inicio": "2026-09-02T14:02:31-03:00",
                     *           "ts_fin": "2026-09-02T14:03:36-03:00",
                     *           "duracion_s": 65,
                     *           "cuadros_confirmados": 309,
                     *           "confianza_media": 0.83,
                     *           "estado": "confirmado",
                     *           "miniatura_url": "/api/v1/evidencias/9874/miniatura",
                     *           "asignado_a": {
                     *             "id": 7,
                     *             "nombre": "Supervisor Losa N3"
                     *           },
                     *           "reincidente": true,
                     *           "aviso_legal": "Indicio automatizado. Requiere validación humana."
                     *         }
                     *       ],
                     *       "contadores": {
                     *         "por_revisar": 34,
                     *         "confirmado": 128,
                     *         "descartado": 41,
                     *         "reincidente": 9,
                     *         "todos": 203
                     *       },
                     *       "siguiente_cursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["PaginaHallazgos"];
                };
            };
            401: components["responses"]["NoAutenticado"];
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerHallazgo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["HallazgoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hallazgo con evidencia, línea de tiempo y trazabilidad de la regla */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallazgoDetalle"];
                };
            };
            403: components["responses"]["SinPermiso"];
            404: components["responses"]["NoEncontrado"];
            "4XX": components["responses"]["Error"];
        };
    };
    triarHallazgo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["HallazgoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionTriage"];
            };
        };
        responses: {
            /** @description Hallazgo actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hallazgo"];
                };
            };
            /** @description Otro usuario ya lo resolvió */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    triarLote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: number[];
                    decision: components["schemas"]["DecisionTriage"];
                };
            };
        };
        responses: {
            /** @description Resultado por hallazgo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 12 */
                        aplicados?: number;
                        omitidos?: {
                            /** Format: int64 */
                            id?: number;
                            /** @example ya resuelto por otro usuario */
                            motivo?: string;
                        }[];
                    };
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    crearAccionCorrectiva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["HallazgoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccionCorrectivaNueva"];
            };
        };
        responses: {
            /** @description Acción creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccionCorrectiva"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    listarVideos: {
        parameters: {
            query?: {
                estado?: "en_cola" | "procesando" | "listo" | "error";
                fuente_id?: components["parameters"]["FuenteId"];
                limite?: components["parameters"]["Limite"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de videos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Video"][];
                        siguiente_cursor?: string | null;
                    };
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    reprocesarVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encolado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerPanel: {
        parameters: {
            query?: {
                /** @description Hora de **captura**, no de procesamiento. */
                desde?: components["parameters"]["Desde"];
                hasta?: components["parameters"]["Hasta"];
                turno?: components["parameters"]["Turno"];
                obra_id?: components["parameters"]["ObraId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indicadores, series y críticos recientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Panel"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    listarReglas: {
        parameters: {
            query?: {
                area_id?: components["parameters"]["AreaId"];
                activa?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reglas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Regla"][];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    crearRegla: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReglaEntrada"];
            };
        };
        responses: {
            /** @description Regla creada en versión 1 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Regla"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerRegla: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReglaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regla */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Regla"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    actualizarRegla: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReglaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReglaEntrada"];
            };
        };
        responses: {
            /** @description Nueva versión de la regla */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Regla"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    simularRegla: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReglaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    desde: string;
                    /** Format: date */
                    hasta: string;
                    regla: components["schemas"]["ReglaEntrada"];
                };
            };
        };
        responses: {
            /** @description Resultado de la simulación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoSimulacion"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerReporte: {
        parameters: {
            query?: {
                segmentacion?: "zona" | "turno" | "camara" | "epp";
                /** @description Hora de **captura**, no de procesamiento. */
                desde?: components["parameters"]["Desde"];
                hasta?: components["parameters"]["Hasta"];
                area_id?: components["parameters"]["AreaId"];
                formato?: "json" | "csv";
            };
            header?: never;
            path: {
                tipo: "ranking-epp" | "zonas" | "mapa-calor" | "tendencia";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reporte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reporte"];
                    "text/csv": string;
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerCatalogos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogos"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerEstado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ingesta: {
                            /** @example true */
                            activa?: boolean;
                            /** @example 1 */
                            en_proceso?: number;
                            /** @example 3 */
                            en_cola?: number;
                        };
                        cobertura: components["schemas"]["Cobertura"];
                        /**
                         * @description El contador que va junto a "Hallazgos" en la barra lateral.
                         * @example 23
                         */
                        pendientes_por_revisar: number;
                    };
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    obtenerSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 7,
                     *       "nombre": "Prevencionista de turno",
                     *       "rol": "prevencionista",
                     *       "area_id": null,
                     *       "permisos": [
                     *         "ver_hallazgos",
                     *         "triar_hallazgos",
                     *         "ver_evidencia",
                     *         "ver_reportes",
                     *         "asignar_acciones"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Sesion"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
}
